### ISSUE TITLE
Call to Imagemagick fails if the dir-name contains blanks

### ISSUE THREAD

**Issue by kludikovsky** [giacmir/Inkscape-JPEG-export-extension#11]
Hi, first of all thank for this great extension.

After installing the extension I got no output.

Following the code I discovreed that the directories are not 'ecaped' consequently throughout the code. Which let the call to IM fail if you have folders like `D:\Eigene Dateien\` as the space terminates the param.

I `exportPage` the `foldername is properly escaped

        `command = "inkscape -C -d %s -e \"%sjpinkexp.png\" -b\"%s\" %s" % (self.options.density, tmp,bgcol, curfile)`

while in tojpeg` the escaping is missing.

        `command = "convert -quality %s -density %s %sjpinkexp.png %s " % (self.options.quality, self.options.density, tmp, outfile)`

after having the dir escaped thi was solved

        `command = "convert -quality %s -density %s \"%sjpinkexp.png\" \"%s\" " % (self.options.quality, self.options.density, tmp, outfile)`

I suggest to escape all locations with the direrctory.

**Comment by giacmir** [comment]
Thanks @kludikovsky for ponting this out. I corrected the escaping in the `tojpeg` method as suggested.

**Comment by kludikovsky** [comment]
Thanks!
