### ISSUE TITLE
Can't run Error in line 7

### ISSUE THREAD

**Issue by chriskyfung** [giacmir/Inkscape-JPEG-export-extension#15]
I have the following error when I try to export to jpeg with the extension.

  File "jpegexport.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

Could you give me a help, please?

**Comment by Moini** [comment]
@chriskyfung : That line looks unsuspicious, it's just a comment. 
Can you attach your version of jpegexport.py? I suspect there has been a copy-paste error or similar.

**Comment by chriskyfung** [comment]
@Moini  Thank you for your reminding.
I knew I have downloaded a HTML file instead of the py file.

**Comment by giacmir** [comment]
Thank you @Moini , your help on this project is really appreciated.

**Comment by Moini** [comment]
It's not an uncommon problem, I've seen this a couple of times already :) 
Hope it'll work for you now, @chriskyfung  :D
@giacmir It's a pleasure :) I'm linking to this repo frequently.
