### ISSUE TITLE
Size JPG

### ISSUE THREAD

**Issue by rsskg** [giacmir/Inkscape-JPEG-export-extension#19]
My image saved with Inkscape PNG format 300Kb.
Then I save this image with GIMP with format JPG, get image with size 80Kb.
But if I save with This extension in JPG with Inkscape, I get image size 200KB
How get size with this extension size 80Kb? More compressed, how GIMP

**Comment by giacmir** [comment]
At this moment the extension hasn't an option to define compression amount of exported images. It could be an intersting feature though.

Do you want to work on it and open a pull request?

**Comment by vanntile** [comment]
I would. Let me see what I can do. Because Now, that I can export .jpg directly makes my life easier, so can I give something back?

**Comment by vanntile** [comment]
As I can see the imagemagick parameters, the compression rate is already set by setting the quality. So I improved the file size by interlacing and subsampling. If it is needed, we could add a selector for the subsampling method (4:4:4, 4:4:2 or 4:2:0)
