### ISSUE TITLE
WebP export option?

### ISSUE THREAD

**Issue by jeffmcneill** [giacmir/Inkscape-JPEG-export-extension#9]
Hi, great plugin. Wondering if there is interest in either creating a similar plugin for WebP?

http://www.imagemagick.org/script/webp.php

**Comment by giacmir** [comment]
Hello, 
at this time I'm not interested nor have time to create a WebP export plugin. Nonetheless it should not be difficult. Probably it is feasible by just changing the imagemagick command run by this plugin.

**Comment by Moini** [comment]
@jeffmcneill : can you tell me the optimal parameters for webp? Then I could include an option to export to webp, but I don't know enough about the format to make a good decision which parameters to use. Or maybe the default setting of imagemagick is already good enough?

**Comment by jeffmcneill** [comment]
Hi, if just want to do a lossless duplicate it is:

````
convert input.png -define webp:lossless=true output.webp
```` 

- Via http://www.imagemagick.org/discourse-server/viewtopic.php?t=25323
- See also http://www.imagemagick.org/script/webp.php, http://www.hongkiat.com/blog/webp-guide/,

**Comment by Moini** [comment]
Great, thanks, @jeffmcneill ! I've updated the extension:
https://github.com/Moini/Inkscape-JPEG-export-extension-webp
 
(I'm not sure if giacmir would want to include it, as it doesn't really fit the name now, but if you can confirm that it works, I will make a pull request nonetheless)

Could you test it for me? The thing is, my imagemagick version does not support webp export, due to https://bugs.launchpad.net/ubuntu/+source/imagemagick/+bug/1117481 ... , so to know if it works, I'll need your help, @jeffmcneill .

**Comment by jeffmcneill** [comment]
Hi, ok I can do that but it needs to wait a few days. I've got some issues with Python and the moment and will have to spend time rebuilding it. I've set my calendar to 1 week. Sorry for the delay, got some client work to get done.

**Comment by Moini** [comment]
@jeffmcneill : did you already have time for some testing?

**Comment by jeffmcneill** [comment]
Sorry guys, I don't. The real issue though is that while WebP is interesting, it causes some trouble because people expect to be able to interact with jpg/png. See: http://www.cnet.com/news/facebook-tries-googles-webp-image-format-users-squawk/

And frankly, I've gotten some very effective scripts for compressing stuff using ImageMagick and ImageOptim-CLI, so adding WebP to the mix won't likely do much for me, and would just add complexity. 

Since my install is somewhat broken, I just do the standard Inkscape export to PNG. Then if needed, I run convert/imageoptim commands. I realize that this very issue is one I personally created, sorry for the drop-off of enthusiasm!

**Comment by Moini** [comment]
What a pity. So testing will need to wait until I'm on LM18 (which may still take a few weeks, and will hopefully work out... - or I'll have to compile my own imagemagick without that silly flag that deactivates webp).

**Comment by Moini** [comment]
Really had to compile it myself, because it still is not part of Ubuntu 16.04. I've confirmed that it works, though. I'll make a pull request now, might still need changes, but I need a graphical diff.

**Comment by giacmir** [comment]
This discussion continues in #12
